{
"HorizonLayout":[
{
"showSearch":true,
"showMenu":true,
"image":"https://a-maash.com/logo.png",
"showLogo":true,
"layout":"logo"
},
{
"layout":"bannerImage",
"items":[
{
"padding":15,
"radius":0,
"category":null,
"image":"https://a-maash.com/wp-content/uploads/2021/02/129712943_233890471431724_2145683483490355597_n-300x114.jpg"
}
],
"isSlider":false
},
{
"layout":"bannerImage",
"design":"default",
"autoPlay":false,
"radius":10,
"items":[
{
"category":44,
"radius":0,
"image":"https://a-maash.com/wp-content/uploads/2021/02/App_Icon-2-300x300.png",
"padding":15
},
{
"image":"https://a-maash.com/wp-content/uploads/2021/02/App_Icon-2-300x300.png",
"category":8,
"padding":15,
"radius":0
},
{
"category":37,
"image":"https://a-maash.com/wp-content/uploads/2021/02/App_Icon-2-300x300.png",
"radius":0,
"padding":15
}
],
"isSlider":true
}
],
"Setting":{
"MainColor":"#3FC1BE",
"ProductListLayout":"list",
"StickyHeader":true,
"ProductDetail":"simpleType"
},
"TabBar":[
{
"layout":"home",
"showChat":false,
"pos":100,
"icon":"assets/icons/tabs/icon-home.png"
},
{
"categoryLayout":"card",
"icon":"assets/icons/tabs/icon-category.png",
"pos":200,
"layout":"category"
},
{
"icon":"assets/icons/tabs/icon-search.png",
"pos":300,
"layout":"search"
},
{
"icon":"assets/icons/tabs/icon-heartthin.png",
"pos":400,
"layout":"wishlist"
},
{
"pos":500,
"showChat":true,
"layout":"profile",
"icon":"assets/icons/tabs/icon-user.png"
}
],
"Drawer":{
"logo":"https://i.imgur.com/18o4YqT.png",
"items":[
{
"show":true,
"type":"home"
},
{
"type":"web",
"show":false
},
{
"show":true,
"type":"about"
},
{
"show":false,
"type":"login"
},
{
"show":true,
"type":"category"
}
]
},
"VerticalLayout":{
"key":"qsddl5owij",
"name":"اخر ‏المحاضرات",
"layout":"list"
},
"SplashScreen":{
"data":"assets/images/splashscreen.png",
"type":"animated"}}
